### ISSUE TITLE
VS scraper does not detect data from daily pdfs

### ISSUE THREAD

**Issue by JudithBouman2412** [openZH/covid_19#405] opened 2020-04-03 09:13 UTC
The VS scraper only detects data from the main website, however, more data is profided in PDF daily. https://www.vs.ch/documents/6756452/7008787/2020%2004%2002%20Sit%20Epid%20-%20%C3%89tat%20Stand.pdf 

These data are not added with the scraper.

**Comment by baryluk** [comment] 2020-04-03 09:57
Duplicate of https://github.com/openZH/covid_19/issues/315

**Closed** 2020-04-03 10:58 UTC
Labels: scraper
