### ISSUE TITLE
NE data not collected anymore

### ISSUE THREAD

**Issue by voisardf** [openZH/covid_19#572] opened 2020-04-22 09:33 UTC
I think data from NE are not collected anymore as the publication format changed.
https://www.ne.ch/autorites/DFS/SCSP/medecin-cantonal/maladies-vaccinations/Pages/Covid-19-statistiques.aspx

**Comment by simgraworldwide** [comment] 2020-04-22 09:41
It is an issue with the scraper, since they publish case numbers only in retrospect. We hope to be able to fix it today.

**Comment by voisardf** [comment] 2020-04-22 10:12
true. I was also confused at first, as numbers here in NE are updated in function of the sampling date and not in function of the day results arrive.
anyway, thanks a lot for your work! 👍

**Comment by metaodi** [comment] 2020-04-22 11:41
Duplicate of #569

**Comment by voisardf** [comment] 2020-04-22 12:09
sorry, haven't seen that one. Feel free to close this issue then.

**Closed** 2020-04-22 14:14 UTC
Labels: scraper
