### ISSUE TITLE
VS Scraper fails

### ISSUE THREAD

**Issue by zdavatz** [openZH/covid_19#313] opened 2020-03-29 16:47 UTC
```
VS 2020-03-29T            -      21 FAILED 2020-03-29T18:30:11+02:00  # URLs: https://www.vs.ch/de/web/coronavirus
```
cc @baryluk

**Comment by metaodi** [comment] 2020-03-29 17:06
Duplicate of #312 

please quickly check if your issue has been submitted already.

**Closed by metaodi** 2020-03-29 17:06 UTC

**Comment by zdavatz** [comment] 2020-03-29 17:11
sorry about that!
