### ISSUE TITLE
SH Scraper fails

### ISSUE THREAD

**Issue by zdavatz** [openZH/covid_19#307] opened 2020-03-29 09:47 UTC
cc @baryluk 
```
SH 2020-03-29T08:00       -       - FAILED 2020-03-29T11:30:08+02:00  # URLs: https://sh.ch/CMS/content.jsp?contentid=3209198&language=DE&_=1584807070095 # Errors: Missing cases. Confirmed cases is None
```

**Comment by metaodi** [comment] 2020-03-29 14:22
Duplicate of #303

**Closed by metaodi** 2020-03-29 14:22 UTC
