### ISSUE TITLE
New column ncumul_deceased_confirmed_by_ct

### ISSUE THREAD

**Issue by zukunft** [openZH/covid_19#641] opened 2020-04-30 12:12 UTC
It looks like in some cases a COVID-19 infection cannot be confirmed by a PCR test ( https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7082661/ ). Instead a CT is used in some cases. It seems that some cantons also include cases only confirmed by CT in the COVID-19 statistic #492 . To differentiate these cases from the cases confirmed by Real-Time Reverse-Transcriptase Polymerase Chain Reaction I suggest to add a new column with a name e.g. like "ncumul_deceased_confirmed_by_ct".

**Comment by metaodi** [comment] 2020-04-30 15:09
Do cantons actually communicate this data? Or just report it to the BAG? Do you know of a canton providing this data?

**Comment by zukunft** [comment] 2020-04-30 15:15
Until now, they do not provide this data. But it could be that this is one of the reasons for the big difference in deceased between the BAG and the canton data. I agree with you that we should be skeptical and wait until we get a confirmation from a canton that they are willing to provide this data. I will try to find out more in the next days.

**Comment by JBeyel** [comment] 2020-06-16 12:51
At least in the case of VD this difference is declared since a very long period. I think it was still in March, when they started to report also cases where people died probably of Covid-19, but are not confirmed which means imho that they were not tested, but showed typical signs of Covid-19. According to the cantonal report of VD of today there are 105 cases of deceased people that are only probable and not confirmed out of 420 deceased in total. But I don't know any other cantonal statistic that makes this difference.

**Comment by adrupp** [comment] 2024-04-18 09:20
Hey @zukunft 
We are considering, archiving this repo, because there is no activity anymore and it seems, there will be no activity in the future 🤞. Otherwise it can be unarchived if necessary.
Therefore we're checking all open issues. What about this one? Is it still important or can you either close this one as completed or close as not planned? Thank you!

**Comment by adrupp** [comment] 2024-04-30 11:37
Friendly reminder (open question):
@zukunft

**Comment by mchaamsler** [comment] 2024-05-05 21:27
Dear @adrup, as the initiator of this initiative, I take the decision to close this issue as "Not Planned". I do not expect that @zukunft would have any objections. Thanks again for your efforts to clean up.

**Closed** 2024-05-06 04:25 UTC
Labels: enhancement
