### ISSUE TITLE
Adapt JU Scraper to scrape ncumul_hosp, ncumul_ICU and deceased

### ISSUE THREAD

**Issue by tlorusso** [openZH/covid_19#256] opened 2020-03-27 09:17 UTC
Currently, the JU scraper does only collect confirmed cases. Hospitalized and ICU cases as well as deceased (still empty) would be available as well:

https://www.jura.ch/fr/Autorites/Coronavirus/Accueil/Coronavirus-Informations-officielles-a-la-population-jurassienne.html

https://github.com/openZH/covid_19/blob/master/fallzahlen_kanton_total_csv/COVID19_Fallzahlen_Kanton_JU_total.csv

**Comment by metaodi** [comment] 2020-03-27 11:27
Related to #237

**Comment by baryluk** [comment] 2020-03-27 22:04
Looks like duplicate of https://github.com/openZH/covid_19/issues/146

**Closed** 2020-03-28 06:48 UTC
